# Generated by Django 2.2 on 2020-08-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service', models.CharField(choices=[('O', 'Change Oil'), ('T', 'Inflate Tires'), ('D', 'Diagnostic')], max_length=1)),
            ],
            options={
                'db_table': 'tickets',
                'ordering': ['id'],
            },
        ),
    ]
