# Generated by Django 2.2 on 2020-08-27 01:36

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ticket',
            managers=[
                ('Ticket Manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
