# Generated by Django 2.2 on 2020-08-27 01:58

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20200827_0136'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ticket',
            managers=[
                ('TicketManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
