# Generated by Django 2.2 on 2020-09-02 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20200827_0158'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ticket',
            managers=[
            ],
        ),
    ]
